root: true
env:
  browser: true
  es2022: true
  node: true
ignorePatterns:
  - .next
  - '*.js'
  - '*.mjs'
  - '*.cjs'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - tailwindcss
extends:
  plugin:tailwindcss/recommended
rules:
  tailwindcss/classnames-order: error
  tailwindcss/enforces-negative-arbitrary-values: error
  tailwindcss/no-custom-classname:
    - error
    - whitelist: []
